### ISSUE TITLE
accept4: too many open files

### ISSUE THREAD

**Issue by jakobrosenberg** [emilevauge/traefik#157] opened 2016-01-09 23:43 UTC
Traefik runs for a few hours without a glitch before these errors start rolling in. Sites behind Traefik then becomes unresponsive and the only solution is to restart Traefik.

```
2016/01/10 00:39:19 server.go:1934: http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 160ms
2016/01/10 00:39:19 server.go:1934: http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 5ms
2016/01/10 00:39:19 server.go:1934: http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 10ms
2016/01/10 00:39:20 server.go:1934: http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 20ms
2016/01/10 00:39:20 server.go:1934: http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 40ms
2016/01/10 00:39:20 server.go:1934: http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 80ms
```

**Comment by stevendborrelli** [comment] 2016-01-10 16:24
https://github.com/emilevauge/traefik/issues/127 might be related.

**Comment by jakobrosenberg** [comment] 2016-01-10 23:20
Traefik is producing the error again after running for probably 10 hours since its last restart.

``ulimit -n`` shows a limit of 1024 open file descriptors.
``ls -l /proc/32098/fd | wc -l`` prints "1024" (32098 is traefik)


``ls -l /proc/32098/fd`` prints
```
lrwx------ 1 root root 64 Jan 10 12:54 0 -> /dev/null
lrwx------ 1 root root 64 Jan 10 12:54 1 -> /dev/pts/1
lrwx------ 1 root root 64 Jan 10 12:54 10 -> socket:[14783002]
lrwx------ 1 root root 64 Jan 10 12:54 100 -> socket:[13848357]
lrwx------ 1 root root 64 Jan 10 23:36 1000 -> socket:[14473062]
lrwx------ 1 root root 64 Jan 10 23:36 1001 -> socket:[14477627]
lrwx------ 1 root root 64 Jan 10 23:36 1002 -> socket:[14474740]
... (~100 lines)
lrwx------ 1 root root 64 Jan 10 23:36 997 -> socket:[14461768]
lrwx------ 1 root root 64 Jan 10 23:36 998 -> socket:[14463145]
lrwx------ 1 root root 64 Jan 10 23:36 999 -> socket:[14463154]
```

I'm running a Meteor application with socket connections (exported as a common node application) which I assume is partially the culprit. The application runs flawless outside of traefik.

**Comment by emilevauge** [comment] 2016-01-12 07:28
Thanks @jakobrosenberg, I will look at that soon

**Comment by emilevauge** [comment] 2016-01-28 18:51
duplicate of #127

**Closed** 2016-02-09 21:49 UTC
Labels: bug
