### ISSUE TITLE
Marathon backend with basic authentication

### ISSUE THREAD

**Issue by zubairov** [emilevauge/traefik#131] opened 2015-11-26 10:56 UTC
First of all - your project looks awesome, and does exactly what I need. 
But. We have a Marathon running with HTTP Basic authentication enabled, and I can't get it working. I tried encoding username/password in URL but still getting this error:

```
ime="2015-11-26T10:52:50Z" level=info msg="Starting provider *provider.Marathon &{baseProvider:{Watch:true Filename:} Endpoint:http://user:password@127.0.0.1:8080/ Domain:marathon.localhost NetworkInterface:lo marathonClient:<nil>}" 
time="2015-11-26T10:52:50Z" level=info msg="Starting provider *main.WebProvider &{Address::9081 CertFile: KeyFile:}" 
time="2015-11-26T10:52:50Z" level=info msg="Preparing server" 
time="2015-11-26T10:52:50Z" level=info msg="Starting server" 
time="2015-11-26T10:52:50Z" level=error msg="Failed to register for subscriptions, No cluster memebers available at the moment" 
time="2015-11-26T10:52:50Z" level=error msg="Failed to create a client for marathon, error: No cluster memebers available at the moment" 
time="2015-11-26T10:52:50Z" level=info msg="Configuration receveived from provider marathon: (*types.Configuration)(nil)" 
time="2015-11-26T10:52:50Z" level=info msg="Last marathon config received more than 2s, OK" 
time="2015-11-26T10:52:50Z" level=info msg="Skipping empty Configuration" 
```

**Comment by emilevauge** [comment] 2015-11-26 10:59
Duplicate of #110  ;)

**Comment by zubairov** [comment] 2015-11-26 11:00
indeed, @emilevauge feel free to close this one

**Comment by emilevauge** [comment] 2015-11-26 11:02
OK, closing it! And thank you for your kind comment :)

**Closed by emilevauge** 2015-11-26 11:02 UTC
Labels: duplicate
