### ISSUE TITLE
Mesos watch feature broken

### ISSUE THREAD

**Issue by rvm2015** [emilevauge/traefik#95] opened 2015-11-04 19:42 UTC
Traefik does not seem to be seeing application changes with the Mesos backend. Using this configuration

    port = ":80"
    graceTimeOut = 10
    traefikLogsFile = "log/traefik.log"
    accessLogsFile = "log/access.log"
    logLevel = "INFO"
    ProvidersThrottleDuration = 5
    [web]
    address = ":18080"
    [marathon]
    endpoint = "http://10.42.0.80:8080"
    networkInterface = "eth0"
    watch = true
    domain = "traefik"

If I deploy new instances traefik is not picking up on additions. If I scale down instances traefik is still routing to the destroyed ones kicking out 502 bad gateways. A recycle of traefik fixes the problem. Not sure if this is related to #81

**Comment by emilevauge** [comment] 2015-11-04 19:49
Hi @rvm2015, which version are you using ?

**Comment by rvm2015** [comment] 2015-11-04 20:00
$ ./traefik --version
    6e1a0554c044f67e05aecd5a1e5c54711b0a7e99 built on the 2015-11-02_03:53:25PM

**Comment by emilevauge** [comment] 2015-11-04 21:26
@rvm2015, I cannot reproduce your issue, upscaling and downscaling is working normally on Traefik on my laptop.
Can you give us your traefik logs using `logLevel = "DEBUG"` during a downscaling?

**Comment by rvm2015** [comment] 2015-11-05 19:29
I will redeploy Traefik this evening with the logging cranked up and get back to you.

**Comment by emilevauge** [comment] 2015-11-09 23:21
Anything new @rvm2015 ?

**Comment by rvm2015** [comment] 2015-11-10 20:17
I pulled the latest version from master and rebuilt it, seems to be working now. Not sure what was going on before but it's good now.

**Comment by vdemeester** [comment] 2015-11-10 20:19
Cool @rvl2015, gonna close this issue for now, but if it happens again, please comment on it I'll reopen :wink:

**Closed by vdemeester** 2015-11-10 20:19 UTC
